site_name: HubCare
site_url: https://cjjcastro.gitlab.io/2019-1-hubcare-docs
repo_name: '2019.1-hubcare-docs'
repo_url: 'https://github.com/fga-eps-mds/2019.1-hubcare-docs'
theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/fga-eps-mds/2019.1-hubcare-docs'

nav:
  - Início: README.md
  - Colaboradores: contributors/README.md
  - Projeto:
    - Documento de Visão: project/vision-document/README.md
    - Documento de Arquitetura: project/architecture-document/README.md
  - Integração:
    - Gerenciamento de Integração: project-integration-management/README.md
    - Termo de Abertura de Projeto: project-integration-management/project-charter/README.md
    - Plano de Gerenciamento de Projeto: project-integration-management/project-management-plan/README.md
  - Qualidade:
    - Modelo de Medição de Repositórios do GitHub: project-quality-management/measurement-model/README.md
  - Riscos:
    - Plano de Gestão de Riscos: project-risk-management/risk-management-plan/README.md
    - Registro dos Riscos: project-risk-management/risk-management-list/README.md
  - Custos: project-cost-management/README.md
  - Roadmap:
    - Roadmap do Produto: product-roadmap/README.md
  - Pipelines:
    - DevOps: pipeline/devops/README.md
    - Pipeline API: pipeline/api/README.md
    - Pipeline Chrome Extension: pipeline/plugin/README.md
    - GitFlow: pipeline/gitflow/README.md
    
  - Treinamentos:
    - Ágil: training/agile/README.md
    - Docker: training/docker/README.md
    - Git: training/git/README.md
    - Tecprog: training/tecprog/README.md
    - Django: training/django/README.md
    - Plugin Chrome: training/plugin_chrome/README.md
    - Testes Unitários: training/unit_test/README.md
  - Sprints:
    - Burndown de Riscos: sprint/burndown-risk/README.md
    - Sprint 1 Planning: sprint/sprint-1-planning/README.md
    - Sprint 1 Review: sprint/sprint-1-review/README.md
    - Sprint 2 Planning: sprint/sprint-2-planning/README.md
    - Sprint 2 Review: sprint/sprint-2-review/README.md
    - Sprint 3 Planning: sprint/sprint-3-planning/README.md
    - Sprint 3 Review: sprint/sprint-3-review/README.md
    - Sprint 4 Planning: sprint/sprint-4-planning/README.md
    - Sprint 4 Review: sprint/sprint-4-review/README.md
    - Sprint 5 Planning: sprint/sprint-5-planning/README.md
    - Sprint 5 Review: sprint/sprint-5-review/README.md
