title: "HubCare"
description: "O Hubcare é um projeto de código aberto para gerenciar se um repositório é bom ou não para um recém-chegado, seja um visitante passageiro, alguém que procura contribuições ou alguém que esteja interessado apenas no software."

url: https://fga-eps-mds.github.io/2019.1-hubcare-docs

version: 35

defaults:
  - scope:
      type: ""
    values:
      layout: "default"

sass:
  style: compressed
  sass_dir: _sass

markdown: kramdown

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

# theme: jekyll-theme-architect